[package]
name = "getting-rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.29.0"}
sdl2 = { version = ">=0.35", features=["gfx","image"] }